/*
   Constructor is a special type of method 
   that's invoked each time an object of a Class is created

   Default Constructor: Constructor that's automatically generated by the compiler.
      incase you don't create any explicitly.
   
   If we declare a constructor explicitly, the default constructor will be removed by compiler.

   Rules for creating a constructor:
   1. unlike other methods, constructor doesn't have any return type
   2. name of constructor of a class must be the same as the name of that class
   3. constructors should be public 
*/

#include<iostream>
using std::string;

class Employee {
  public:
    string Name;
    string Company;
    int Age;

    Employee(string name, string company, int age) {
      Name = name;
      Company = company;
      Age = age;
    };

    void IntroduceYourself() {
      std::cout<<"Name: "<<Name<< std::endl;
      std::cout<<"Company: "<<Company<< std::endl;
      std::cout<<"Age: "<<Age<<std::endl;
    };
};

int main() {
  Employee employee1 = Employee("Saldina", "YT_CodeBeauty", 25);
  employee1.IntroduceYourself();

  Employee employee2 = Employee("John", "Amazon", 35);
  employee2.IntroduceYourself();
};