#use command "make SHELL=cmd"

main:
	C:\masm32\bin\ml /c /coff /Cp hello1.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello1.obj
	hello1

main2:
	C:\masm32\bin\ml /c /coff /Cp hello2.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello2.obj
	hello2.exe

main4:
	C:\masm32\bin\ml /c /coff /Cp hello4.asm
	C:\masm32\bin\link -entry:main /subsystem:console hello4.obj
	hello4